# -*- coding: utf-8 -*-
"""BTCNN(nhandienmonan).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tDdHvs86ff75vyCSaiydsvQ5DuuUmzLs
"""

from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
train_dir="/content/drive/MyDrive/Ảnh/món ăn"
img_width,img_height=280,280
batch_size=32

train_datagen=ImageDataGenerator(
    rescale=1.0/255,
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest')

from google.colab import drive
drive.mount('/content/drive')

train_generator=train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_width,img_height),
    batch_size=batch_size,
    class_mode='categorical')

model=Sequential([
    Conv2D(32,(3,3),activation='relu',padding='same',input_shape=(img_width,img_height,3)),
    MaxPooling2D(pool_size=(2,2)),
    Conv2D(64,(3,3),activation='relu',padding='same'),
    MaxPooling2D(pool_size=(2,2)),
    Conv2D(64,(3,3),activation='relu',padding='same'),
    Flatten(),
    Dense(128,activation='relu'),
    Dropout(0.5),
    Dense(5,activation='softmax')
])
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

history=model.fit(train_generator,epochs=50)

from keras.utils import load_img
import numpy as np
import matplotlib.pyplot as plt

path='/content/miquang.JPG'
img=load_img(path,target_size=(280,280))
plt.imshow(img)
plt.show()
img=np.array(img)
img=img/255.0
img=np.expand_dims(img, axis=0)
prediction=np.argmax(model.predict(img))
class_labels={v:k for k,v in train_generator.class_indices.items()}
ten=class_labels[prediction]
print(f'Tên món ăn này là:{ten}')

model.save('nhandiendoan.h5')